name: PHP Composer

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Install yarn
      run: curl -o- -L https://yarnpkg.com/install.sh | bash
    
    - name: Install JS dependencies
      run: yarn install
    
    - name: Build assets
      run: grunt build
      
    - name: Run test suite
      run: composer run-script test
